import type { GetStaticProps, NextPage } from 'next';

import { usePageMetadata } from '../hooks/usePageMetadata';
import { PageInterface } from '../interfaces';
import { client } from '../common/contentfulClientProvider';
import { Cookie } from '../components/ui/svg';

import { Heading, Page, Container, PageHeader, Text } from '../components/atomic-design/atoms';

import {
  PageHeaderContainer,
  QualityContent,
  ValuesContent,
  MainContent,
} from '../styles/pages/cookies-styles';

interface Props {
  pages: PageInterface[];
  content: PageInterface[];
}

const CookiesPage: NextPage<Props> = ({ pages }) => {
  const { title, description, keywords } = usePageMetadata(pages, 'cookies');

  return (
    <Page title={title} description={description} keywords={keywords}>
      <Container>
        <PageHeaderContainer>
          <PageHeader>
            <span>
              Why we use <div>cookies</div>?<b>.</b>
            </span>
          </PageHeader>
          <Cookie ariaLabel="cookie icon" />
        </PageHeaderContainer>
      </Container>
      <MainContent>
        <ValuesContent>
          <Container size="sm">
            <Heading variant="h4">What are "cookies"?</Heading>
            <Text>
              First of all, they are "good" files, small and simple, that are installed in your
              browser device once you have given us permission to do so. They are not files that
              take up space on your computer, or malicious, or anything close to it, and they
              fulfill many objectives that help to improve your experience on our website more and
              more. No website should install these files on your device without first asking your
              permission. By having your consent, we are respecting your privacy and complying with
              what the law in many countries requires of all web platforms.
            </Text>
          </Container>
        </ValuesContent>
        <QualityContent>
          <Container size="sm">
            <Heading variant="h4">Ok, but... why do we use cookies?</Heading>
            <Text>
              Because we are interested in you having the best user experience browsing our site.
              These light files that cookies give us are used by your browser to give us
              information, for example, about the number of visits we receive and help us to have a
              more specific idea of ​​the movement generated by our website.
            </Text>
            <Text>
              In our case, we use the Google Analytics cookie to keep a count of visits, statistics
              of each page and information necessary to improve our services day by day.
            </Text>
          </Container>
        </QualityContent>
        <ValuesContent>
          <Container size="sm">
            <Heading variant="h4">How do I disable or enable these cookies?</Heading>
            <Text>
              You can do it in 5 simple steps and as always our friend Google can explain it to you
              super clearly and in detail, better than us. We leave you this{' '}
              <a
                href="https://support.google.com/accounts/answer/61416?hl=es-419&co=GENIE.Platform%3DDesktop"
                target="_blank"
              >
                link
              </a>{' '}
              to the Google help service so you can perform this action from your computer, phone,
              iPad or device that you are using.
            </Text>
            <Text>
              With this page we want to put you in tune with why we use cookies and we will tell you
              very briefly so as not to bore you. If you want to know more about cookies and
              everything they imply, we leave you this{' '}
              <a href="https://policies.google.com/technologies/cookies?hl=es" target="_blank">
                link
              </a>
              .
            </Text>
          </Container>
        </ValuesContent>
      </MainContent>
    </Page>
  );
};

export default CookiesPage;

export const getStaticProps: GetStaticProps = async () => {
  const res = await client.getEntries({ content_type: 'pages' });
  return {
    props: {
      pages: res?.items,
    },
  };
};
